version: '3.8'

services:
  mysql-db:
    image: arm64v8/mysql:latest  
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: yo
      MYSQL_USER: yodb
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  rabbitmq:
    image: arm64v8/rabbitmq:management 
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: yoni
      RABBITMQ_DEFAULT_PASS: pass

  node-backend:
    build: ./
    restart: always
    ports:
      - "3000:3000"                    

volumes:
  mysql-data:

